### ISSUE TITLE
Uncaught ReferenceError: AppExclusionType is not defined

### ISSUE THREAD

**Issue by shahzib111** [clover/remote-pay-cloud#171] opened 2020-12-25 22:49 UTC
I recently upgraded from angular 7 to angular 10 and for some reason i am getting the following error

`Uncaught ReferenceError: AppExclusionType is not defined
    at Object.gGmd (AppExclusionType.js:12)
    at __webpack_require__ (bootstrap:79)
    at Object.WpDk (index.js:10)
    at __webpack_require__ (bootstrap:79)
    at Object.wvk5 (index.js:8)
    at __webpack_require__ (bootstrap:79)
    at Object.qk9L (index.js:2)
    at __webpack_require__ (bootstrap:79)
    at Module.VjSG (main.js:5067)
    at __webpack_require__ (bootstrap:79)`

**Comment by david-clover-com** [comment] 2020-12-25 23:17
What version of the sdk are you using?

**Comment by shahzib111** [comment] 2020-12-25 23:40
@david-clover-com thanks for helping out, I'm using ask version 4.0.4. The latest.

**Comment by david-clover-com** [comment] 2020-12-26 01:02
Can you push up a simple example repo and provide steps on reproducing the issue?

**Comment by shahzib111** [comment] 2020-12-26 05:24
I will try to work on that but upon researching my issue is similar to this https://community.clover.com/questions/26157/clover-with-angular.html. Once I upgraded from angular 7 to 8, I encountered this issue. It points to the same file mentioned in the link above.

**Comment by david-clover-com** [comment] 2020-12-26 14:05
I couldn't reproduce that as described in the original answer. I did find some other problems and made some changes which were released in 4.0.4.

**Comment by shahzib111** [comment] 2020-12-27 18:01
the issue seems to be in remote-pay-cloud-api. Found a workaround. please see https://github.com/clover/remote-pay-cloud-api/issues/48 for more details

**Comment by david-clover-com** [comment] 2020-12-28 15:17
Yes, that is where the model is.

**Comment by david-clover-com** [comment] 2021-01-19 15:58
Fixed in remote-pay-cloud-api, available in 4.0.5.

**Closed as completed by david-clover-com** 2021-01-19 15:58 UTC
